eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIGSERVER
      profile: dev
  application:
    name: api-gateway
server:
  port: 8090
