eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082
spring:
  application:
    name: Informations
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3308/sys?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
