env: env1212
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8087
spring:
  application:
    name: product
  datasource:
    username: root
    password: 123456
    url:   jdbc:mysql://localhost:3308/pm10?useUnicode=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.1.15
    username: guest
    password: guest
    port: 5672
